#!/usr/bin/env bash
# ck-archive-shard.sh — time-shard archived.md to archived/<YYYY-MM>.md
# + a GENERATED archived/INDEX.md (V5 / I.archived-shard / T3).
# Splits the flat archived.md by the `## Archived YYYY-MM-DD` block
# headers into per-month shard files; generates an id→shard INDEX;
# removes the flat file. grep-by-id spans SPEC + all shards.
#
#   ck-archive-shard.sh [--dry-run] [--threshold N=500] [archived.md]
#
# Noop when ≤ threshold lines. Merges into existing shards if present.
set -euo pipefail

THRESHOLD=500
DRY=0
ARCHIVE="archived.md"

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY=1 ;;
        --threshold)
            THRESHOLD="$2"
            shift
            ;;
        --threshold=*) THRESHOLD="${1#*=}" ;;
        -h | --help)
            sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        --*)
            echo "ck-archive-shard: unknown option: $1 (see --help)" >&2
            exit 2
            ;;
        *) ARCHIVE="$1" ;;
    esac
    shift
done

[ -f "$ARCHIVE" ] || {
    echo "ck-archive-shard: no such file: $ARCHIVE" >&2
    exit 2
}

lines="$(wc -l <"$ARCHIVE" | tr -d ' ')"
if [ "$lines" -le "$THRESHOLD" ]; then
    echo "ck-archive-shard: $ARCHIVE = $lines lines ≤ threshold $THRESHOLD — noop"
    exit 0
fi

ARCHIVE_DIR="$(dirname "$ARCHIVE")/archived"

# Count distinct months to report shard count.
shard_count="$(grep -cE '^## Archived [0-9]{4}-[0-9]{2}-[0-9]{2}' "$ARCHIVE" || true)"
if [ "$shard_count" -eq 0 ]; then
    echo "ck-archive-shard: no dated archive blocks found — noop"
    exit 0
fi
# Distinct months (a month may appear in multiple blocks).
distinct_shards="$(grep -oE '^## Archived [0-9]{4}-[0-9]{2}' "$ARCHIVE" |
    awk '{ print substr($3, 1, 7) }' | sort -u | wc -l | tr -d ' ')"

if [ "$DRY" = 1 ]; then
    echo "ck-archive-shard: DRY-RUN — would shard $ARCHIVE ($lines lines) into $distinct_shards shard(s)"
    exit 0
fi

mkdir -p "$ARCHIVE_DIR"

# Split archived.md into per-month shard files. Each `## Archived YYYY-MM-DD`
# header routes subsequent lines to archived/YYYY-MM.md (appending if the
# shard already exists — merges with prior sharding runs).
awk -v dir="$ARCHIVE_DIR" '
  BEGIN { shard = "" }
  /^## Archived [0-9]{4}-[0-9]{2}-[0-9]{2}/ {
    month = substr($3, 1, 7)
    shard = dir "/" month ".md"
    print "" >> shard
    print $0 >> shard
    next
  }
  shard != "" { print >> shard }
' "$ARCHIVE"

# Regenerate INDEX.md from ALL shard files in archived/.
# Scans for §T/§B rows (`| <ID> `) and §V/§C/§I rows (`- <ID>: `).
idx="$ARCHIVE_DIR/INDEX.md"
{
    echo "# archived/ INDEX"
    echo ""
    echo "Generated by ck-archive-shard — do not edit."
    echo ""
    echo "| id | shard |"
    echo "| --- | --- |"
} >"$idx"

for shard in "$ARCHIVE_DIR"/????-??.md; do
    [ -f "$shard" ] || continue
    month="$(basename "$shard" .md)"
    awk -v m="$month" '
      /^\| [TB][0-9]+ / { printf "%s\t%s\n", $2, m }
      /^- [A-Z][0-9]+: / { id = $2; sub(/:$/, "", id); printf "%s\t%s\n", id, m }
    ' "$shard"
done |
    sort -t'	' -k1,1V |
    awk -F'\t' '{ printf "| %s | %s |\n", $1, $2 }' \
        >>"$idx"

rm -f "$ARCHIVE"

echo "ck-archive-shard: sharded $ARCHIVE ($lines lines) → $distinct_shards shard(s) + INDEX.md"
